swagger: '2.0'
info:
  title: Registration API
  version: '1.0'
paths:
  /register/:
    post:
      summary: Register a swimmer for a competition
      description: Register a swimmer for a specific competition and assign them to a lane number. Only one swimmer from a team can be registered simultaneously.
      tags:
        - Registration
      parameters:
        - in: body
          name: registration
          description: Registration data
          required: true
          schema:
            type: object
            required:
              - swimmer_id
              - line_no
              - competition_id
            properties:
              swimmer_id:
                type: string
                description: Unique identifier of the swimmer (UUID)
              line_no:
                type: integer
                description: Lane number for the swimmer
              competition_id:
                type: integer
                description: Unique identifier of the competition
      responses:
        200:
          description: Swimmer successfully registered
          schema:
            type: object
            properties:
              status:
                type: string
                example: "ok"
        400:
          description: Bad request - invalid data or registration forbidden
          schema:
            type: object
            properties:
              status:
                type: string
                example: "failed"
              reason:
                type: string
                enum:
                  - "no data"
                  - "invalid json"
                  - "invalid data"
                  - "registration forbidden"
                  - "integrity error"
              error:
                type: string
                description: Error details if applicable
        403:
          description: Access denied. Only allowed from localhost.
        500:
          description: Internal server error - database error
          schema:
            type: object
            properties:
              status:
                type: string
                example: "failed"
              reason:
                type: string
                example: "database error"

  /unregister/:
    post:
      summary: Unregister a swimmer from a competition
      description: Unregister a swimmer from a specific competition by changing their registration state to inactive.
      tags:
        - Registration
      parameters:
        - in: body
          name: unregistration
          description: Unregistration data
          required: true
          schema:
            type: object
            required:
              - swimmer_id
              - competition_id
            properties:
              swimmer_id:
                type: string
                description: Unique identifier of the swimmer (UUID)
              competition_id:
                type: integer
                description: Unique identifier of the competition
      responses:
        200:
          description: Swimmer successfully unregistered
          schema:
            type: object
            properties:
              status:
                type: string
                example: "ok"
        400:
          description: Bad request - invalid data
          schema:
            type: object
            properties:
              status:
                type: string
                example: "failed"
              reason:
                type: string
                enum:
                  - "no data"
                  - "invalid json"
                  - "invalid data"
              error:
                type: string
                description: Error details if applicable
        403:
          description: Access denied. Only allowed from localhost.
        500:
          description: Internal server error - database error
          schema:
            type: object
            properties:
              status:
                type: string
                example: "failed"
              reason:
                type: string
                example: "database error"

tags:
  - name: Registration
    description: Manage swimmer registration
